

networks:
  inception:
    name: inception

volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/imqandyl/Desktop/Inception/data/database
  web-data:
    name: web-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/imqandyl/Desktop/Inception/data/web

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web-data:/var/www/html
    networks:
      - inception # Ensure nginx is connected to the same network as other services
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - web-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    environment: # Add environment variables for database setup
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

#docker compose up --build : build the Docker image from your Dockerfile Then it will start the container, and Nginx will run in the foreground
#built your Nginx image using Debian as the base and installed Nginx.
#we need to tell php that it needs to accept FastCGI request from address “wp-php:9000”, the localhost of our wordpress-php container at port 9000. in 41 line config

#volumes : Because we are installing wordpress to the container that runs php, we need to actually have access to the hosting service aka nginx, so that we can access the wordpress pages
#Docker created a web folder and it mounted the contents of /var/www/html to it.
